version: 2

builds:
    - main: ./cmd/cobid
      ldflags:
          - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
      env:
          - CGO_ENABLED=0
          - GOPRIVATE=github.com/catalogfi/*
      goos:
          - linux
          - darwin
          - windows
      goarch:
          - amd64
          - arm64

checksum:
    name_template: "checksums.txt"

snapshot:
    name_template: "{{ .Tag }}-next"

archives:
    - format: tar.gz
      # this name template makes the OS and Arch compatible with the results of `uname`.
      name_template: >-
          {{ .ProjectName }}_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
          {{- if .Arm }}v{{ .Arm }}{{ end }}
      # use zip for windows archives
      format_overrides:
          - goos: windows
            format: zip

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"

release:
    prerelease: auto
