services:
    cobi_redis:
        image: redis:alpine
        container_name: cobi_redis
        ports:
            - 6379:6379
        volumes:
            - ~/.cobi/cobi_data:/data
    cobi:
        build:
            context: .
            dockerfile: Dockerfile
        image: ghcr.io/catalogfi/cobi:latest
        container_name: cobi
        depends_on:
            - cobi_redis
        restart: unless-stopped
        env_file:
            - .env
