name: Go Releaser

on:
    push:
        tags:
            - "*"
jobs:
    goreleaser:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Go environment
              uses: actions/setup-go@v5
              with:
                  go-version: "1.20.x"

            - name: Install Dependencies
              run: |
                  git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
                  go mod tidy

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v6
              with:
                  distribution: goreleaser
                  version: latest
                  args: release --clean --verbose
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
